In [149]:
from UserDAO import UserDAO

In [150]:
a=2

In [151]:
a

2

In [152]:
dao = UserDAO("./formation.db")
# list(dao.findAll())

def __del__(self)


In [153]:
# ! pip install numpy pandas

In [154]:
import numpy as np
x = np.arange(15, dtype=np.int64)


In [155]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [156]:
x.reshape(3, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [157]:
x.reshape(3, 5).max(axis=1)

array([ 4,  9, 14])

In [158]:
x.reshape(3, 5).max(axis=0)

array([10, 11, 12, 13, 14])

In [159]:
import pandas as pd
users = dao.findAll()

df_users = pd.DataFrame(users)
df_users

id first_name last_name                       email       gender  \
0       1     Walden    Kirsop       wkirsop0@buzzfeed.com         Male   
1       2    Damaris   Chmarny       dchmarny1@weather.com       Female   
2       3    Roderic   Rennick        rrennick2@discuz.net         Male   
3       4     Ashlee  Tringham  atringham3@telegraph.co.uk       Female   
4       5        Cam  Stothert    cstothert4@moonfruit.com   Non-binary   
..    ...        ...       ...                         ...          ...   
995   996     Lesley   Gaffney        lgaffneyrn@google.ca         Male   
996   997      Maxim   Hutchin     mhutchinro@slashdot.org         Male   
997   998      Leona   Viccary          lviccaryrp@dot.gov       Female   
998   999      Beale  Skotcher     bskotcherrq@twitter.com         Male   
999  1000    Pebrook  Eslemont    peslemontrr@hatena.ne.jp  Genderfluid   

          ip_address  
0         84.2.121.2  
1      200.32.224.56  
2       247.191.3.33  
3    150.119.233.121  
4     105.203.32.161  
..               ...  
995   136.101.215.24  
996     11.89.158.51  
997  204.179.108.188  
998   86.168.127.111  
999    13.187.116.51  

[1000 rows x 6 columns]

In [160]:
df_users.head()

id first_name last_name                       email      gender  \
0   1     Walden    Kirsop       wkirsop0@buzzfeed.com        Male   
1   2    Damaris   Chmarny       dchmarny1@weather.com      Female   
2   3    Roderic   Rennick        rrennick2@discuz.net        Male   
3   4     Ashlee  Tringham  atringham3@telegraph.co.uk      Female   
4   5        Cam  Stothert    cstothert4@moonfruit.com  Non-binary   

        ip_address  
0       84.2.121.2  
1    200.32.224.56  
2     247.191.3.33  
3  150.119.233.121  
4   105.203.32.161

In [161]:
df_users.tail()

id first_name last_name                     email       gender  \
995   996     Lesley   Gaffney      lgaffneyrn@google.ca         Male   
996   997      Maxim   Hutchin   mhutchinro@slashdot.org         Male   
997   998      Leona   Viccary        lviccaryrp@dot.gov       Female   
998   999      Beale  Skotcher   bskotcherrq@twitter.com         Male   
999  1000    Pebrook  Eslemont  peslemontrr@hatena.ne.jp  Genderfluid   

          ip_address  
995   136.101.215.24  
996     11.89.158.51  
997  204.179.108.188  
998   86.168.127.111  
999    13.187.116.51

In [162]:
# df_users.info()
df_users.describe()

id
count  1000.000000
mean    500.500000
std     288.819436
min       1.000000
25%     250.750000
50%     500.500000
75%     750.250000
max    1000.000000

In [163]:
df_users.columns
df_users['first_name']

0       Walden
1      Damaris
2      Roderic
3       Ashlee
4          Cam
        ...   
995     Lesley
996      Maxim
997      Leona
998      Beale
999    Pebrook
Name: first_name, Length: 1000, dtype: object

In [164]:
df_users.loc[995]

id                             996
first_name                  Lesley
last_name                  Gaffney
email         lgaffneyrn@google.ca
gender                        Male
ip_address          136.101.215.24
Name: 995, dtype: object

In [165]:
# df_users[df_users['gender']=="Male"]
df_users[(df_users['gender']=="Male") & (df_users['email'].str.contains('.com'))]

id  first_name    last_name                          email gender  \
0      1      Walden       Kirsop          wkirsop0@buzzfeed.com   Male   
6      7       Leroi       Bodega             lbodega6@hexun.com   Male   
12    13  Maximilian  Serraillier    mserraillierc@delicious.com   Male   
13    14    Tremaine     Farguhar           tfarguhard@hc360.com   Male   
15    16    Ezequiel       Tommeo           etommeof@walmart.com   Male   
..   ...         ...          ...                            ...    ...   
982  983      Rudolf        Leefe               rleefera@ask.com   Male   
983  984     Hillary     Girardin            hgirardinrb@mac.com   Male   
984  985      Lenard   Derrington  lderringtonrc@marketwatch.com   Male   
990  991   Gualterio     MacManus      gmacmanusri@angelfire.com   Male   
998  999       Beale     Skotcher        bskotcherrq@twitter.com   Male   

         ip_address  
0        84.2.121.2  
6      59.250.25.59  
12      21.38.1.123  
13    237.33.32.181  
15    214.15.80.122  
..              ...  
982  140.212.247.64  
983  54.122.182.146  
984   198.33.117.48  
990  56.105.118.205  
998  86.168.127.111  

[279 rows x 6 columns]

In [ ]:
# df_users['upper_last_name'] = df_users['last_name'].map(lambda d:d.upper())
df_users['upper_last_name'] = df_users['last_name'].str.upper()
